---
output: html_document
---

## Notes on Anhui Longitudinal data analysis for SH

#### Thursday 27.10.2016

Recieved questionairres from SH. files `EnglishQuestionnaire2001` to `2015` in `data/questionnaires`. 
2001 queationnaire starts with "two years ago.." which is obiously an error!?
Additional querries about these questionnaires: 2001, 2003 and 2006 have Q903 "which year is it" as the correct answer "sheep". Obvs not true so this is some post festum stuff going on. 

Correct name of survey is: *"The Longitudinal Study of Older People in Anhui Province, China"*

Although in first four questionnaires it is referred to as Chaohu region - this region no longer exists, actually not sure if it ever was a region, the city also seems to not exist any longer or rather Wikipedia says "On August 22, 2011, Anhui province government announced in a controversial decision[1] that Chaohu was split into three parts and was absorbed by neighboring cities." 

Found and registered for Naitonal Archive o Computerised data on Ageing - http://www.icpsr.umich.edu/icpsrweb/NACDA/studies/36388 is the study link, but only for 2001 and 2003 waves. But full datasets for both are there. Accessd and dowloaded 27.10/ in `data/archives/ICPSR_36388-2001` and `data/archives/ICPSR_36388-2003`. Quote: "These data are available to the general public."


Citation: Silverstein, Merril, and Shuzhou Li. The Longitudinal Study of Older People in Anhui Province, China, 2001-2003. ICPSR36388-v1. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2016-05-16. http://doi.org/10.3886/ICPSR36388.v1

Persistent URL: http://doi.org/10.3886/ICPSR36388.v1


[[Sons and Daughters:Adult Children’s Care for Elderly Parents at the End of Life in Rural China]] says
that since 2003 a mortality questionnaire was also used? But these are not in the files SH sent. 

Meeting with SH:

- wants to see if ANHUI dataset will show any vestigal effects of great famine (1959–1961) and/or cultural revolution (1966-76) on late life well being. so not just individual level events as is normally looked at, but national events. [cf Minton and me on mortality surfaces, and 1918 ripple in particular, SH remembers Rowena XY sth on flu mortality as well. Can't google who she is, ask SH. ]

- given the cutoff point was 60 in 2001, both these events would have occurred when the respondents were 18 and 25 respectively at the youngest. 

- If Anhui doesn't look good for that, it is worth looking at CHARLS - one of the HRS surveys - China Health and Retirement Longitudinal Study [http://charls.ccer.edu.cn/en]

- 27.10. MZ signed up for CHARLS data - academic research licence

- MZ to go through available documentation on Anhui to try to reconstruct what the survey is, as well as available publications, and write up a "can you please confirm" type letter for Huijun. 



#### Tuesday 1.11.2016

Applied for CHARLS individual datasets for all 3 waves plust two pilots. 

Recieved two mortality questionnaires from Huijuin, saved in `data/questionnaires/EnglishQuestionnaireDeath` for 2003 (same as 2006, 09 and 12) and 2015.



#### Thursday 3.11.2016

Received Charls full datasets. Saved in `data/charls/CHARLS_Life_History_Data/`. Originally in Stata 13 format, backsaved in Stata to version 12. 

This is the 2014 wave 3 - life history survey

- Demographic_backgrounds = 20,543, 1920 variables
- Education_History = 20,496 obs 1105 variables
- Family_Infomration = 20,452 obs 473 variables
- Health_History = 20,492 obs, 86 variables 
- Wealth_History = 20.418 obs, 440 vars
- Residence = 20,654 obs, 935 vars
- Work_History = 20,484 obs, 2024 vars
- Sample_Infor = 20,948 obs, 8 vars

#### Friday 4.11.2016

Huijun sends over table of repondent counts. 

|Wave	|Time|	Size	|Follow-up Valid Sample	|Replenished Valid Sample|	Death	|Moved	|Village|
|--|------------|------|--------|-----|--|--|-|
|1 |	2001.04 	|1,800 |	1,715 |	— 	|— 	|— |	— |
|2 |	2003.11 	|1,715 |	1,391 |	— 	|240| 	76| 	—| 
|3 |	2006.12 	|1,391 |	1,067 |	— 	|236| 	57| 	—| 
|4 |	2009.06 	|1,067 |	808 	|416 (60-67 years old）| 	173 |	33| 	—| 
|5 |2012.09 |	808+416=1,224 |	977 |	— 	|181 |	46| 	—| 
|6 |2015.09 |	1243 |	763 |	 480 (60-65 years old） |	160 |	15 |	64| 



Compared to available information from publications it is still not clear - or inconsistent. Following quesitons:

1. What does "village" mean? 
2. Is this correct: Follow-up Valid Sample + Death + Moved = Size - Missing(refused). So this means there were 8, 31, 53, 20 and 39 missing in waves 2-6?
3. Is the size in row 6 actually 977, not 1243?
4. What are the 64 in the last row?
5. Is there any more information on the replenished sample? 
6. Is it true that:
- waves 1-3 the youngest participants are born 1941
- waves 4-5 the youngest participants are born 1949
- wave 6 there are 480 people born between 1950 and 1955
7. What about inconsistencies with published studies? Zuo, Dongmei and Li, Shuzhuo (2013) say there are 605 follow up in wave 5, and don't mention a replenishment in wave 4?
8.Do you have information on the numbers of children in each wave?

